# Expose app on port 80 to later get handled by load balancer.
apiVersion: v1
kind: Service
metadata:
  name: {{ include "jwt-api.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "jwt-api.name" . }}
    helm.sh/chart: {{ include "jwt-api.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "jwt-api.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
