# Default values for ccpay-api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

# Environment variables -- Don't include secrets (creds, tokens, etc)!
# PORT must be distinct per env. dev = 02 , staging = 01, master = 00
env:
  APP_PORT: '9002'
  DB_HOST: '10.8.0.3'
  DB_USER: 'dev-jwtapi'
  DB_NAME: 'dev_DB'
  REDIS_HOST: '10.8.1.3'
  DB_DIALECT: 'postgres'

secrets:
  DB_PASSWORD: ''
  REDIS_PASSWORD: ''
  SECRET: ''

# App Service
service:
  type: ClusterIP
  port: 9002


# Setup access from outside of the K8S Cluster
ingress:
  hosts:
    - host: dev.jwt.api.rocketops.io
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - hosts:
        - dev.jwt.api.rocketops.io
      # Change name of cert to staging or prod respectively!
      secretName: jwtapi-dev-cert-prod